### ISSUE TITLE
Master does not compile with intel compiler anymore

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/arbor#169]
There are currently two issues:

#### First issue
```
/users/karakasv/Devel/nestmc-proto/tests/modcc/test.cpp(10): error: no instance of "regex_replace" matches the argume
nt list
            argument types are: (std::string, std::regex, const char [1])
      return !expr? "null": regex_replace(expr->to_string(), csi_code, "");
                            ^

compilation aborted for /users/karakasv/Devel/nestmc-proto/tests/modcc/test.cpp (code 2)
```

This is probably due to the fact that the intel compiler's implementation of `regex_replace` does not recognise as it ought to the last `const char*` argument and needs to be wrapped inside an `std::string()`.

#### Second issue

This was introduced with the `lmorpho` package:

```
/users/karakasv/Devel/nestmc-proto/src/util/optional.hpp(103): error: no instance of overloaded function "nest::mc::$til::uninitialized<X>::construct [with X=swc_emitter]" matches the argument list
            argument types are: (swc_emitter)
            object type is: nest::mc::util::uninitialized<swc_emitter>
                  data.construct(std::forward<T>(init));
                       ^
          detected during:
            instantiation of "nest::mc::util::detail::optional_base<X>::optional_base(bool, T &&) [with X=swc_emitte$, T=swc_emitter]" at line 239
            instantiation of "nest::mc::util::optional<X>::optional(X &&) [with X=swc_emitter]" at line 428
            instantiation of "nest::mc::util::optional<X> nest::mc::util::just(X &&) [with X=swc_emitter]" at line 9$ of "/users/karakasv/Devel/nestmc-proto/lmorpho/lmorpho.cpp"

/users/karakasv/Devel/nestmc-proto/src/util/optional.hpp(103): error: no instance of overloaded function "nest::mc::$til::uninitialized<X>::construct [with X=pvector_emitter]" matches the argument list
            argument types are: (pvector_emitter)
            object type is: nest::mc::util::uninitialized<pvector_emitter>
                  data.construct(std::forward<T>(init));
                       ^
          detected during:
            instantiation of "nest::mc::util::detail::optional_base<X>::optional_base(bool, T &&) [with X=pvector_em$tter, T=pvector_emitter]" at line 239
            instantiation of "nest::mc::util::optional<X>::optional(X &&) [with X=pvector_emitter]" at line 428
            instantiation of "nest::mc::util::optional<X> nest::mc::util::just(X &&) [with X=pvector_emitter]" at li$e 95 of "/users/karakasv/Devel/nestmc-proto/lmorpho/lmorpho.cpp"

compilation aborted for /users/karakasv/Devel/nestmc-proto/lmorpho/lmorpho.cpp (code 2)
```

I'm currently investigating this.

**Comment by vkarak** [comment]
The root cause of the second issue is that for the intel compiler the constructor of the `ofstream` is not even moveable. As a result, the `= default` implementation of the move constructor of the `swc_emitter` is just deleted, therefore disabling the `construct()` methods of the `uninitialized`. The following snippet compiles fine with gcc (tested it on 5.3), but fails with the intel compiler:

```c++
#include <fstream>
#include <iostream>
#include <type_traits>

template <bool V, typename R = void>
using enable_if_t = typename std::enable_if<V, R>::type;

template <typename T>
using enable_if_copy_constructible_t =
    enable_if_t<std::is_copy_constructible<T>::value>;

template <typename T>
using enable_if_move_constructible_t =
    enable_if_t<std::is_move_constructible<T>::value>;

template <typename... T>
using enable_if_constructible_t =
    enable_if_t<std::is_constructible<T...>::value>;


struct C {
    explicit C(int n) : n_(n) {}

    C(C&& other) = default;

    int n_;
    std::ofstream os_;
};


int main() {
    C a(10);
    C b(std::move(a));

    return 0;
}
```

The error is the following:

```
foo.cpp(42): error: function "C::C(const C &)" (declared implicitly) cannot be referenced -- it is a deleted function
      C b(std::move(a));
          ^
```

I suspect that the intel compiler does not define any move constructor at all, so it just tries to call the const-ref one, which shall be deleted according to the standard.

**Comment by halfflat** [comment]
Yep, it's definitely the 'forgot to implement `std::fstream` move constructor' issue. This was a problem with libstdc++ before gcc version 5, and there's no simple workaround.

I'm presuming that the intel compiler installation is pointing to a set of old (pre version 5) gnu libstdc++ headers.

**Comment by vkarak** [comment]
> I'm presuming that the intel compiler installation is pointing to a set of old (pre version 5) gnu libstdc++ headers.

Looks like that. Loading a recent GCC after having loaded the intel compiler, it solves the problem. The default system g++ is 4.8.5, so I suppose that icpc looks into these headers for the standard library.

> EDIT: This could also well explain the regex issue.

Yes, it does.

**Comment by halfflat** [comment]
Shall we make this a WONTFIX?

**Comment by bcumming** [comment]
Not a bug: this is misconfiguration of the build. It is annoying, and catches me every time I go to use the Intel compiler, but there isn't much we can do.

**Comment by vkarak** [comment]
> Shall we make this a WONTFIX?

I would say yes.
